
// This is auto-generated class.
// DO NOT EDIT THIS FILE MANUALLY

// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class RemixRegular {
  const RemixRegular._();

  static const String _fontFamily = "Remix Icons Regular";
  static const String _fontPackage = "remix_icons_flutter";

  static const IconData youtube = IconData(0xf101, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData warehouse = IconData(0xf102, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData wallet = IconData(0xf103, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData verified = IconData(0xf104, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData users = IconData(0xf105, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData user = IconData(0xf106, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData unlink = IconData(0xf107, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData twitter = IconData(0xf108, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData trash = IconData(0xf109, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData timer = IconData(0xf10a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData support = IconData(0xf10b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData store_for_good = IconData(0xf10c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData stora = IconData(0xf10d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData star = IconData(0xf10e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData shopping_cart = IconData(0xf10f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData shopping_bag = IconData(0xf110, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData shopping_bag_add = IconData(0xf111, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData shop = IconData(0xf112, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData shield_keyhole = IconData(0xf113, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData share = IconData(0xf114, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData search = IconData(0xf115, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData ruler = IconData(0xf116, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData road_map = IconData(0xf117, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData question_circle = IconData(0xf118, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData question_answer = IconData(0xf119, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData qr = IconData(0xf11a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData profile = IconData(0xf11b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData plus = IconData(0xf11c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData phone = IconData(0xf11d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData pen = IconData(0xf11e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData notifications = IconData(0xf11f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData navigation = IconData(0xf120, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData more = IconData(0xf121, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData minus = IconData(0xf122, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData message = IconData(0xf123, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu = IconData(0xf124, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_right = IconData(0xf125, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData map = IconData(0xf126, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData map_pin = IconData(0xf127, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData luggage_cart = IconData(0xf128, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData loyalty = IconData(0xf129, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData loop = IconData(0xf12a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData logout = IconData(0xf12b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData lock = IconData(0xf12c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData linkedin = IconData(0xf12d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData link = IconData(0xf12e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData lifebuoy = IconData(0xf12f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData layout_grid = IconData(0xf130, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData instagram = IconData(0xf131, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData information_circle = IconData(0xf132, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData image = IconData(0xf133, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData history = IconData(0xf134, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData heart = IconData(0xf135, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData handbox = IconData(0xf136, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData global = IconData(0xf137, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData gift = IconData(0xf138, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData fullscreen = IconData(0xf139, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData focus = IconData(0xf13a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData filter = IconData(0xf13b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData file = IconData(0xf13c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData file_shield = IconData(0xf13d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData file_list = IconData(0xf13e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData file_info = IconData(0xf13f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData file_edit = IconData(0xf140, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData file_copy = IconData(0xf141, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData file_1 = IconData(0xf142, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData facebook = IconData(0xf143, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData eye = IconData(0xf144, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData eye_off = IconData(0xf145, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData error_triangle = IconData(0xf146, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData error_circle = IconData(0xf147, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData envelope = IconData(0xf148, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData discount = IconData(0xf149, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData code = IconData(0xf14a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData close = IconData(0xf14b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData close_circle = IconData(0xf14c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData chevron_up = IconData(0xf14d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData chevron_up_small = IconData(0xf14e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData chevron_right = IconData(0xf14f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData chevron_right_small = IconData(0xf150, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData chevron_left = IconData(0xf151, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData chevron_left_small = IconData(0xf152, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData chevron_down = IconData(0xf153, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData chevron_down_small = IconData(0xf154, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData checkbox_circle = IconData(0xf155, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData check = IconData(0xf156, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData check_circle = IconData(0xf157, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData chat = IconData(0xf158, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData category = IconData(0xf159, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData card = IconData(0xf15a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData camera = IconData(0xf15b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData calendar = IconData(0xf15c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData building = IconData(0xf15d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData box = IconData(0xf15e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData bar_chart = IconData(0xf15f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData ban_circle = IconData(0xf160, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData arrow_right = IconData(0xf161, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData arrow_left = IconData(0xf162, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData arrow_left_right = IconData(0xf163, fontFamily: _fontFamily, fontPackage: _fontPackage);

}
